chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX

input:
  pattern: "{chromosome}.vcf.gz"

modules:
  bcftools:
    - perl
    - gsl/2.5
    - bcftools/1.21

  plink:
    - plink/2.0-alpha-6.2

  quick_pcair:
    - gcc/13.2.0
    - openjdk/20.0.0
    - R/4.4.2
    - quick-pcair/1.1.0

resources:
  index_vcf:
    threads: 2
    mem_mb: 2000

  intersect_variants:
    threads: 4
    mem_mb: 8000

  summarize_intersection:
    threads: 1
    mem_mb: 2000

  merge_chromosome:
    threads: 4
    mem_mb: 8000

  concatenate_chromosomes:
    threads: 4
    mem_mb: 8000

  exclude_samples:
    threads: 4
    mem_mb: 8000

  convert_vcf_to_plink:
    threads: 4
    mem_mb: 16000

  run_quick_pcair:
    threads: 8
    mem_mb: 64000
